### ISSUE TITLE
Data request for species Canary rockfish

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/nwfscDiscard#4]
### Identify the common name(s)

Canary rockfish

### Type of data needed

discard totals/rates and biological data

### Gear grouping

Commercial fleet structure is planned as two fleets. 

1. Trawl gear - consisting of a combination of bottom trawl, midwater trawl, shrimp trawl
2. Non-trawl gear - consisting of a combination of fixed gear, hook and line, pot

### Areas

Area specific fleets are based on state: Washington, Oregon, California

### Do you you have clearance to access these data with a valid 2023 NDA form with WCGOP?

- [X] I agree that I have clearance

**Comment by chantelwetzel-noaa** [comment]
@brianlangseth-NOAA Thank you for submitting the data request form. There is one more piece of information that will be needed from you that I failed to include in the form; the length bin structure for your model.  @andi-stephens-NOAA will use this information to provide discarded length composition data.  Based on past experience, I also suggest that the shrimp trawl data be excluded from the trawl gear grouping since the discarded fish from this fleet are particularly small. @andi-stephens-NOAA can you provide the discard length compositions for the the shrimp trawl, other trawl gears, and the non-trawl gear group as described above?

**Comment by brianlangseth-NOAA** [comment]
By length bin structure, do you mean supplying the expected length bins (e.g. 2-60 by 2 cm)? I have not yet thought of that, and would need to get back to you on that.

**Comment by andi-stephens-NOAA** [comment]
Yes, 2-60 by 2 cm would be a fine format for your request.

**Comment by brianlangseth-NOAA** [comment]
Previous assessment used length bins starting at 12-66 cm in increments of 2 cm. I see no reason to change

**Comment by andi-stephens-NOAA** [comment]
Very good.  I'll get that to you shortly.

Cheers,

--Andi

**Comment by chantelwetzel-noaa** [comment]
@brianlangseth-NOAA Did you receive the composition data?  Is so, I am going to close this issue.

**Comment by andi-stephens-NOAA** [comment]
I hadn't heard back from you about the EM data and confidentiality issues.
What have you figured out?

**Comment by chantelwetzel-noaa** [comment]
@andi-stephens-NOAA I wasn't sure you whether you fill this request since I think the timing was slightly before our discussion based on the thornyhead situation.  If you have not completed this lets keep this open.  I will send you a direct email about the path forward with the data as a whole.

**Comment by brianlangseth-NOAA** [comment]
I have not yet seen it or been told where to get it. I will await Andi letting me know, and appreciate splitting out of shrimp trawl from other trawl gears.

**Comment by andi-stephens-NOAA** [comment]
Hi Brian,  we've sorted out the issues with divergent confidentiality code, and your comps are now in 

\\nwcfile\Assessment Data\2023 Assessment Cycle\canary rockfish\WCGOP\Canary_WCGOP_ByState_Trawl-NonTrawl.xlsx

Let me know if you have any problems accessing the file or if you find any anomalies -- or if you need a different stratification.

Cheers,

--Andi

**Comment by andi-stephens-NOAA** [comment]
Closing as I've provided the comps.

**Comment by chantelwetzel-noaa** [comment]
@andi-stephens-NOAA

**Comment by brianlangseth-NOAA** [comment]
Thanks you two. I will let you know if I have questions.

**Comment by brianlangseth-NOAA** [comment]
@chantelwetzel-noaa and @andi-stephens-NOAA I see the bootstrap estimates are included in the file. Im unfamiliar with these. Would you advise using the bootstrapped or the observed values for discarded and retained fish?

**Comment by chantelwetzel-noaa** [comment]
The bootstap is primarily performed in order to generate a standard deviation estimate for the non-catch share data which is needed if you are going to model discard.  In the past, I have used the observed discard rate and not the bootstrap rate for the input rate. However, I suspect the observed rate and the bootstrap rate should be fairly similar depending upon the bootstrap sample size. For canary, if you are not modeling discard, I think using the observed rate is fine.

**Comment by brianlangseth-NOAA** [comment]
Thanks @chantelwetzel-noaa . Yes, the bias is quite low for all but 1 or 2 entries.
