### ISSUE TITLE
Data request for Rex sole (Glyptocephalus zachirus)

### ISSUE THREAD

**Issue by somros** [pfmc-assessments/nwfscDiscard#6]
### Identify the common name(s)

PACFIN Codes: "REX"  "REX1"
PACFIN Common names: "REX SOLE"      "NOM. REX SOLE"

### Type of data needed

discard totals/rates

### Gear grouping

We would like to get data for Trawl and Non-trawl gear, if possible

### Areas

If possible, we would like to get data at State level (Washington, Oregon, California)

### Length bins for discard compositions

Min: 2 cm
Max: 60 cm
Bin size: 2 cm

### Additional information

We request the data as part of the Applied Stock Assessment class (FISH 576) at UW. Please reach out to alberto.rovellini@noaa.gov if I omitted any necessary information

### Do you you have clearance to access these data with a valid 2023 NDA form with WCGOP?

- [X] I agree that I have clearance

**Comment by chantelwetzel-noaa** [comment]
The data requests needs to align with the fleet structure that is used in the assessment model. There are limitations on how disaggregated the data can be provided. Additionally, the uncertainty around discard rates is bootstrapped so the estimate is dependent on the fleet structure for the non-catch share fishery sectors (for rex sole this will likely only apply prior to 2011) creating issues if the data are provided in a more disaggregated form.  Finally, the composition data can be provided at the bin structure requested since these data can more easily be condensed down to the data bin selected in the model. However, since the discard total and rates cannot be processed yet it may be easiest to wait on the biological data request given that once the fleets have been determine there may be a clearer idea of the data bin range for the model.  

I am going to close this request for now and request that a new request be submitted when the fleets are set for clarity in the records.
