### ISSUE TITLE
Data request for Rex sole (Glyptocephalus zachirus)

### ISSUE THREAD

**Issue by somros** [pfmc-assessments/nwfscDiscard#7]
### Identify the common name(s)

PACFIN Codes: "REX" "REX1"
PACFIN Common names: "REX SOLE" "NOM. REX SOLE"

### Type of data needed

discard totals/rates and biological data

### Gear grouping

Trawl gear (all trawl gear types aggregated)

### Areas

North (WA+OR) and South (CA)

### Length bins for discard compositions

Min: 2 cm
Max: 60 cm
Bin size: 2 cm

### Additional information

We request the data as part of the Applied Stock Assessment class (FISH 576) at UW. This request was revised based on feedback on a previous request.

Please reach out to alberto.rovellini@noaa.gov if I omitted any necessary information.

### Do you you have clearance to access these data with a valid 2023 NDA form with WCGOP?

- [X] I agree that I have clearance

**Comment by chantelwetzel-noaa** [comment]
@andi-stephens-NOAA The confidentiality check have passed for the discard and catch data. Once you confirm confidentiality on the biological data we can post these data to the network.

@somros @okenk @melissahaltuch-NOAA @gertsevv In the meantime I recommend looking over the WCGOP documents linked in the readme for this repository to familiarize yourself on WCGOP and the data they collect.  The observed discards and retained catch data will be split into two groups: catch-share and non-catch share.  The catch share program began in 2011 and these vessel have 100% observer coverage so there little no uncertainty around these data. In contrast the non-catch share vessels only have partial observer coverage so a bootstap is performed on the data to estimate uncertainty.  WCGOP produces a groundfish expanded multi-year mortality report (GEMM) based on the data they collect. This data product can be helpful to not only see what the expanded discard mortality estimates but also the proportion of the exploitation arising from the non-catch share and catch-share sectors. The GEMM data can be obtained using the [{nwfscSurvey::pull_gemm}](https://github.com/pfmc-assessments/nwfscSurvey/blob/main/R/pull_gemm.R) function.

**Comment by andi-stephens-NOAA** [comment]
@chantelwetzel-noaa @somros @okenk @melissahaltuch-NOAA @gertsevv 

The data for Rex have no confidentiality issues.  I've put the comps in:

Z:\Assessment Data\2023 Assessment Cycle\rex sole\Rex_WCGOP_WAOR-CA_Trawl-NonTrawl.xlsx

**Comment by somros** [comment]
@chantelwetzel-noaa @andi-stephens-NOAA Thank you Chantel and Andi for walking us through this

**Comment by chantelwetzel-noaa** [comment]
I have added the discard amounts to the same location. There are two files: catch share and non-catch share. Given that the fleets structure will not be based on non- or catch shares, typically people either use the rate that is representative of the major source of mortality (e.g., trawl in the catch share sector) or weight the two rates together if the mortality is split between the sectors. Since the non-catch share vessels do not full observer coverage the amount of observed discard and retained catch is only representative of the trips observed and not the total from non-catch share vessels.  To understand the percent of mortality between non- and catch shares I recommend looking at the GEMM. Let us know if there are any additional questions about the data.
