### ISSUE TITLE
Sebastolobus alascanus

### ISSUE THREAD

**Issue by shipmadison** [pfmc-assessments/nwfscDiscard#8]
### Identify the common name(s)

**Shortspine thornyhead**, channel cod, shortspine channel rockfish, spinycheek rockfish, idiotfish, fagiano, arasuka kichiji, bonehead, gurnard, gurnet, hardhead, hooligan, idiotfish, loe-finned rockfish, roundfin rockfish, scorpion, slim thornhead, thornhead

### Type of data needed

discard totals/rates

### Gear grouping

Trawl and non-trawl

### Areas

North [Washington and Oregon] and South [California]

### Length bins for discard compositions

Minimum length: 6 cm
Maximum length: 72 cm
Size bins: 2 cm
Number of length bins: 34

### Additional information

These data are being requested as part of the Applied Stock Assessment Class (FISH 576) at the University of Washington.

### Do you you have clearance to access these data with a valid 2023 NDA form with WCGOP?

- [X] I agree that I have clearance

**Comment by chantelwetzel-noaa** [comment]
I have processed the data grouping the gear as: 

Trawl: Bottom Trawl, Midwater Trawl, Shrimp Trawl
Non-Trawl (Fixed Gears): Hook & Line, Pot, Fixed Gears 

@andi-stephens-NOAA I have determined the confidentiality of the discard rates. There are no issues for most years except for 4 strata combinations: 2018, 2019, and 2021 CA Fixed Gears under Catch Shares and 2020 WA Fixed Gears under Catch Shares. I have removed the data for these four years and can provide rates for all other years and stratas.  I don't think the biological data will encounter similar confidentiality issues since those data are not split based on catch shares.

**Comment by andi-stephens-NOAA** [comment]
Biological compositions for SSPN for WAOR and CA, Trawl and Non-Trawl,
lengths 6-72 by 2cm are in:

\\nwcfile\FRAM\Assessment Data\2023 Assessment Cycle\shortspine
thornyhead\WCGOP\SSPN_WCGOP_WAOR-CA_Trawl-NonTrawl.xlsx

Let me know if you have any questions, or need anything further.

Cheers,

--Andi

**Comment by chantelwetzel-noaa** [comment]
@okenk @melissahaltuch-NOAA @gertsevv @owenhamel The discard rates have also been added to the network.
